name: my_factory_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  # خفضنا Dart SDK لـ 3.5.0 لضمان التوافق مع أغلب سيرفرات GitHub دون مشاكل
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # الأساسيات
  http: ^1.2.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  
  # الذكاء الاصطناعي والصوت (المهم لمشروعنا)
  speech_to_text: ^6.1.1 # نسخة مستقرة جداً
  flutter_tts: ^4.2.2
  
  # قواعد البيانات والملفات
  supabase_flutter: ^2.5.3
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  
  # الموقع والحساسات
  geolocator: ^10.1.0
  camera: ^0.10.5+5
  
  # الواجهة
  get: ^4.6.6
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # استخدمنا نسخة مستقرة لتقليل التحذيرات

flutter:
  uses-material-design: true
