name: Manual Build Factory

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'اكتب اسم التطبيق هنا'
        required: true
        default: 'Pizzaki'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.0' # هنا نحدد النسخة التي نريدها بالضبط

      - name: Change App Name (Manifest)
        run: |
          # تغيير اسم التطبيق الظاهري للمستخدم
          sed -i 's/android:label=".*"/android:label="${{ github.event.inputs.app_name }}"/' android/app/src/main/AndroidManifest.xml

      - name: Update Pubspec Name
        run: |
          # تحويل الاسم لحروف صغيرة وبدون مسافات ليتوافق مع معايير فلاتر
          CLEAN_NAME=$(echo "${{ github.event.inputs.app_name }}" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          sed -i "s/^name: .*/name: $CLEAN_NAME/" pubspec.yaml

      - name: Flutter Clean & Get
        run: |
          flutter clean
          flutter pub get

      - name: Decode Keystore
        # تأكد من إضافة SIGNING_KEY في Secrets الخاصة بالريبو كـ Base64
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > android/app/key.jks

      - name: Build Signed APK
        run: |
          # بناء نسخة APK فقط لتسريع الوقت في البداية، أو كلاهما كما طلبت
          flutter build apk --release --split-per-abi
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks

      - name: Build Signed AAB
        run: |
          flutter build appbundle --release
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.inputs.app_name }}-Build"
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab
