name: Manual Build Factory

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'اكتب اسم التطبيق هنا'
        required: true
        default: 'Pizzaki'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # تم حذف خطوة الحقن لأننا هنعدل الملف يدوياً في الريبو
      
      - name: Change App Name (Manifest)
        run: |
          sed -i 's/android:label=".*"/android:label="${{ github.event.inputs.app_name }}"/' android/app/src/main/AndroidManifest.xml

      - name: Update Pubspec Name
        run: |
          CLEAN_NAME=$(echo "${{ github.event.inputs.app_name }}" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          sed -i "s/^name: .*/name: $CLEAN_NAME/" pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > android/app/key.jks

      - name: Build Signed APK & AAB
        run: |
          flutter build apk --release
          flutter build appbundle --release
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.inputs.app_name }}-Build"
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
