name: Build Flutter APK

on:
  repository_dispatch:
    types: [build_apk]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # الخطوة الأهم: حقن الكود القادم من Supabase داخل ملف main.dart
      # 1. تغيير كود الصفحة
      - name: Inject Custom Code
        shell: bash
        run: |
          cat << 'EOF' > lib/main.dart
          ${{ github.event.client_payload.page_code }}
          EOF

      - name: Change App Name
        run: |
          sed -i 's/android:label=".*"/android:label="${{ github.event.client_payload.app_name }}"/' android/app/src/main/AndroidManifest.xml
     
      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > android/app/key.jks

      - name: Build Signed APK
        run: |
          flutter build apk --release \
            --dart-define=APP_NAME=${{ github.event.client_payload.app_name }}
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks

      - name: Build Signed AAB
        run: flutter build appbundle --release
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.client_payload.app_name }}-builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
